### ISSUE TITLE
[WIP] Adding Edit and Delete Buttons to Recipe Details

### ISSUE THREAD

**Issue by emmorris1100** [12DaysOfCoding/WeTheFoodies#10]
**Is your feature request related to a problem? Please describe.**
Currently unable to delete or edit recipe entries.

**Describe the solution you'd like**
Adding Edit and Delete Buttons to the Recipe Detail page, allowing for users to edit and delete their recipes.

**Describe alternatives you've considered**
N/A

**Additional context**
- We might need help from backend for implementing delete and edit functions
- ~~Also for potentially reusing the "Add Recipe" page to load the recipe contents for editing~~
- New "Recipe Edit" HTML and javascript for this edit function
- Edit function could be a combination of Delete previous recipe + Add newly edited recipe

We're currently working on this feature on the edit-and-delete branch

**Comment by p8gonzal** [comment]
For backend, enable edit button to profile same form as add-recipe.html
