### ISSUE TITLE
Unable to edit the recipe without first having a difficulty level

### ISSUE THREAD

**Issue by nglu** [12DaysOfCoding/WeTheFoodies#31]
**Describe the bug**
When creating a recipe, if the user forgot to choose a difficulty level and submit the recipe. Later on the user cannot edit the recipe due to uncaught TypeError for data fetching (there was no difficulty defined so there's nothing to fetch from)

**To Reproduce**
1. Create a recipe without difficulty level (totally doable, without any warning)
2. Submit the recipe
3. Edit the recipe
4. You will see empty fields in instructions & ingredients

**Solution**
Force the user to choose a difficulty level like we did in 'Name', 'Time', 'Serving size'

**Comment by p8gonzal** [comment]
Addressed by @emmorris1100
