### ISSUE TITLE
UML Proposals

### ISSUE THREAD

**Issue by p8gonzal** [12DaysOfCoding/WeTheFoodies#7]
This is done when:

- [ ] We have UML proposals for Database Schemas and strengths/weaknesses of profile flow

**Comment by bghoang** [comment]
can it just be something similar to this? Not familiar with the standard UML layout so I just made something https://www.figma.com/file/RRGJnNMeRfeeLptANniwRi/CSE-112-UML-Proposals?node-id=3%3A10
